### ISSUE TITLE
Add repo auth the repo URL

### ISSUE THREAD

**Issue by xrow** [k3s-io/helm-controller#159] opened 2022-09-27 10:22 UTC
Hi,

I think this is a feature. I wanted to configure authorization for private repo this seems to be not possible at the moment. If this is the case please consider this feature request.

**Comment by brandond** [comment] 2022-09-27 11:00
Duplicate of https://github.com/k3s-io/helm-controller/issues/100

**Closed by brandond** 2022-09-27 11:00 UTC
